### GENERAL ###

[environment]
day_from = "09:00:00"
day_to = "17:00:00"
measure_step = 10
publish_step = 15

[broker]
address = "http://localhost:8000"
client_id = "aoRkHPRIXwdHqpcpxpQhacbmFyWkKXwr"
password = "password"

### SENSORS ###

[sensor."dht11"]
type = "DHT11"
gpio = 7

[sensor."water"]
type = "WaterLevel"
gpio = 25

### SWITCHES AND THEIR RULES ###

[switch."lights"]
gpio = 0
rule = "(10:59 < time) & (time < 21:57)"

[switch."heater"]
gpio = 2
rule = "dht11.temperature < 22"

[switch."humidifier"]
gpio = 3
oscillation_step = 5000
rule = "(dht11.humidity < 60) & (water.signal = 1)"
