### GENERAL ###

[environment]
day_from = "09:00:00"
day_to = "17:00:00"
# How ofter perform measurements, default each 10 seconds.
#measure_step = 10000
measure_step = 1000
# How to agregate data, default each 10 minutes.
#publish_step = 600000
publish_step = 6000

[broker]
address = "http://localhost:8091"
client_id = "yFBgI2YP"
password = "okaUbDf4apVzyKII0YdbODi4YwnM9GYU"

### SENSORS ###

[sensor."dht11"]
type = "DHT11"
gpio = 7

[sensor."water"]
type = "Signal"
gpio = 25

### SWITCHES AND THEIR RULES ###

[switch."lights"]
gpio = 0
rule = "(10:59 < time) & (time < 21:57)"

[switch."heater"]
gpio = 2
rule = "dht11.temperature < 22"

[switch."humidifier"]
gpio = 3
oscillation_high_ms = 2000
oscillation_low_ms = 8000
rule = "(dht11.humidity < 60) & (water.signal = 1)"
