### GENERAL ###

[environment]
day_from = "09:00:00"
day_to = "17:00:00"
measure_step = 5000
publish_step = 600000

[broker]
address = "http://localhost:8091"
client_id = "GGcv1919"
password = "s3ShpZ0YHebsaywa3H4n7yGPWUt3rZwb"

### SENSORS ###

[sensor."dht11"]
type = "DHT11"
gpio = 7

[sensor."water"]
type = "Signal"
gpio = 25

### SWITCHES AND THEIR RULES ###

[switch."lights"]
gpio = 0
rule = "(10:59 < time) & (time < 21:57)"

[switch."heater"]
gpio = 2
rule = "dht11.temperature < 22"

[switch."humidifier"]
gpio = 3
oscillation_high = 2000
oscillation_low = 8000
rule = "(dht11.humidity < 60) & (water.signal = 1)"
