# GNU Make workspace makefile autogenerated by Premake

.NOTPARALLEL:

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif


ifeq ($(config),debug)
  TerraPi_config = debug
endif
ifeq ($(config),release)
  TerraPi_config = release
endif

PROJECTS := TerraPi

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

TerraPi:
ifneq (,$(TerraPi_config))
	@echo "==== Building TerraPi ($(TerraPi_config)) ===="
	@${MAKE} --no-print-directory -C src -f Makefile config=$(TerraPi_config)
endif

clean:
	@${MAKE} --no-print-directory -C src -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   TerraPi"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"