version: '3'

services:
  broker:
    build: broker
    image: terrapi_broker
    container_name: terrapi_broker
    volumes:
      - ${PWD}/broker/mosquitto.conf:/etc/mosquitto/mosquitto.conf:ro
    ports:
      - "8883:8883"
  web:
    build: web
    image: terrapi_web
    container_name: terrapi_web

volumes:
  mosquitto.conf:
