version: "3.3"

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: terrapi
      POSTGRES_PASSWORD: password
      POSTGRES_DB: terrapi
    ports:
      - 5432:5432
    volumes:
      - ./tmp/postgres-data:/var/lib/postgresql/data
